#****************************************************************************************
# Yaml formate to manage entire lifcycle of containers
# We define four stages as of now viz:
# 1. Tak registration 
# 2. Service creation 
# 3. Service updates
# 4. Service deletion
# Assumption: 
#      - Images are available in ECR repo or docker-hub
#      - Cluster is up and running with container instances
# More information : http://boto3.readthedocs.io/en/latest/reference/services/ecs.html
# *****************************************************************************************
containers:
  - appname: Test
    family: TEST
    taskRoleArn: ''
    containerDefinitions:
     - cpu: 200
       memory: 2048
       memoryReservation: 1024
       portMappings:
         - hostPort: 0
           containerPort: 9080
       # We can use docker-hub images as well
       image: 953030164212.dkr.ecr.us-east-1.amazonaws.com/test-service
       name: test
       essential: True
       privileged: False
       mountPoints:
       - sourceVolume: logs
         containerPath: /var/log/test-app/
         readOnly: False
       environment:
          - name : APP_ENV
            value: dev
          - name: CONF_HOME
            value: /opt/apps-java/config
          # This environment variable is for registrator to identify service
          - name: SERVICE_NAME
            value: test
       dockerLabels:
           name: test-service-containers
       dockerSecurityOptions:
           - no-new-privileges
    volumes:
      - name: logs
        host:
          sourcePath: /var/log/apps/
    # ***********************************************************************************************************
    # Service parameters will be used to create service
    # We can add load balancers alo if required.
    # Please visit : http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.create_service
    # ***********************************************************************************************************
    serviceCreate:
      - cluster: applications-dev
        serviceName: test-service
        # Task definition is family:revision. 
        # Creat service on latest revision and use update to roll back o deploy new version
        taskDefinition: TEST
        desiredCount: 2
        clientToken: test-service
        deploymentConfiguration:
           maximumPercent: 200
           minimumHealthyPercent: 50
    # ******************************************************************
    # Service Update parameters will be used to update running service 
    # ******************************************************************
    serviceUpdate:
      - cluster: applications-dev
        serviceName: test-service
        # Desired count also can be updated via commandlinee
        desiredCount: 2
        # Specify task def revision to roll back 
        taskDefinition: TEST
        deploymentConfiguration:
           maximumPercent: 200
           minimumHealthyPercent: 50
    # **********************************************************************
    # Service dlete will be used to delete services where running count is 0 
    # Cannot be used via automated tools as it requires user confimration
    # **********************************************************************
    serviceDelete:
      - cluster:  applications-dev 
        serviceName: test-service
